stages:
  - build_and_test
  - deploy
  - deploy_check

variables:
  URL_STATIC_SITE: 'http://katskobucket.s3-website.eu-north-1.amazonaws.com/'

build_and_test:
  stage: build_and_test
  image: node:18
  script:
    - npm install -g htmlhint
    - npm install -g csslint
    - npm install -g prettier    
    - htmlhint .
    - csslint "style.css"  
    - prettier --write "script.js"
  artifacts:
    paths:
      - ./

deploy to s3:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp ./ s3://$S3_BUCKET --recursive

deploy check:
  stage: deploy_check
  script:
    - STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $URL_STATIC_SITE)
    - if [ "$STATUS_CODE" -eq "200" ]; then
        echo "Success! Status code is 200.";
      else
        echo "Failed! Status code is $STATUS_CODE.";
        exit 1;
      fi

